# render.yaml

services:
  - type: web
    name: itraveda-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn itraveda:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: itraveda-db
          property: connectionString

databases:
  - name: itraveda-db
    plan: free
