services:
  - type: web
    name: itraveda
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn itraveda:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: <your_postgres_database_url>  # Replace this if needed
